integrate ensenso_camera nxlibrary for camera launching

diff --git a/flowstate_ensenso/flowstate/Dockerfile.service b/flowstate_ensenso/flowstate/Dockerfile.service
--- a/flowstate_ensenso/flowstate/Dockerfile.service
+++ b/flowstate_ensenso/flowstate/Dockerfile.service
@@ -23,37 +23,41 @@ ADD src/flowstate-ros-camera-drivers/flowstate_common /opt/ros/underlay/src/flow
 ADD src/sdk-ros /opt/ros/underlay/src/sdk-ros
 
 # Install build dependencies.
-RUN . /opt/ros/jazzy/setup.sh && \
-    apt-get update && \
+RUN apt-get update && \
     apt-get install -y \
     python3-rosdep \
     python3-colcon-common-extensions \
     ros-jazzy-ament-cmake-vendor-package \
     git \
     wget \
-    python3-pip \
-    && rosdep init || true && \
-    rosdep update && \
-    wget -O ensenso.deb "https://download.optonic.com/s/ensensosdk/download?files=ensenso-sdk-${ENSENSO_VERSION}-x64.deb" && \
+    python3-pip
+
+RUN rosdep init || true && \
+    rosdep update
+
+RUN wget -O ensenso.deb "https://download.optonic.com/s/ensensosdk/download?files=ensenso-sdk-${ENSENSO_VERSION}-x64.deb" && \
     apt-get install -y ./ensenso.deb && \
-    rm ensenso.deb && \
-    cd /opt/ros/underlay/src/ && \
+    rm ensenso.deb
+
+ENV ENSENSO_INSTALL=/opt/ensenso
+
+RUN cd /opt/ros/underlay/src/ && \
     git clone https://github.com/ensenso/ros_driver && \
     cd ros_driver && \
     # Run the prepare script for ROS2 for Ensenso
-    ./.github/scripts/prepare_ros2_build.sh && \
-    cd /opt/ros/underlay && \
-    # Install pip dependency (required by Ensenso ROS2 driver)
-    pip3 install transforms3d --break-system-packages || true && \
-    cd /opt/ros/underlay/src/ && \
-    git clone https://github.com/codebot/rmw_zenoh -b morganquigley/jazzy_with_old_attachment_metadata_format && \
-    cd rmw_zenoh && git checkout 05cdda05a7c5e7c2871e6d85bfc9411546a529c4 && cd /opt/ros/underlay && \
-    rosdep install --from-paths src --ignore-src --rosdistro jazzy -y --skip-keys "snapshot_interfaces OrbbecSDK" && \
-    colcon build \
-        --continue-on-error \
-        --event-handlers=console_direct+ \
-        --merge-install \
-        --packages-up-to intrinsic_sdk \
+    export ROS_VERSION=2 && ./.github/scripts/prepare_ros2_build.sh
+
+RUN pip3 install transforms3d --break-system-packages || true
+
+RUN cd /opt/ros/underlay/src/ && \
+    git clone https://github.com/codebot/rmw_zenoh -b morganquigley/jazzy_with_old_attachment_metadata_format
+
+RUN cd /opt/ros/underlay/src/rmw_zenoh && \
+    git checkout 05cdda05a7c5e7c2871e6d85bfc9411546a529c4
+
+RUN cd /opt/ros/underlay && \
+    . /opt/ros/jazzy/setup.sh && \
+    rosdep install --from-paths src --ignore-src --rosdistro jazzy -y --skip-keys "snapshot_interfaces OrbbecSDK roscpp message_runtime catkin tf rostest nodelet message_generation actionlib rospy roslint ensenso_camera" \
     && rm -rf /var/lib/apt/lists/* \
     && rm -rf /root/.ros/rosdep
 
@@ -63,6 +67,18 @@ RUN . /opt/ros/jazzy/setup.sh \
         --event-handlers=console_direct+ \
         --merge-install \
         --packages-up-to=rmw_zenoh_cpp
+
+RUN . /opt/ros/jazzy/setup.sh && \
+    . /opt/ros/underlay/install/setup.sh && \
+    cd /opt/ros/underlay && \
+    colcon build \
+        --event-handlers=console_direct+ \
+        --merge-install \
+        --packages-up-to flowstate_camera_common ensenso_camera \
+        --cmake-args -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-Wno-error=invalid-constexpr -Wno-invalid-constexpr -Wno-deprecated-declarations"
+
+RUN echo "Copying missing Ensenso wrapper headers..." && \
+    cp -r /opt/ros/underlay/src/ros_driver/ensenso_camera2/include/* /opt/ros/underlay/install/include/
 
 RUN echo "Searching for and copying vendored libprotobuf..." && \
     find /opt/ros/underlay/build -name "libprotobuf.so.29.0.0" -exec cp {} /opt/ros/underlay/install/lib/ \; || true
@@ -93,6 +109,7 @@ RUN . /opt/ros/jazzy/setup.sh \
       --event-handlers=console_direct+ \
       --merge-install \
       --packages-above-and-dependencies=${SERVICE_PACKAGE} \
+      --cmake-args -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-Wno-error=invalid-constexpr -Wno-invalid-constexpr -Wno-deprecated-declarations" \
     && rm -rf /opt/ros/overlay/build /opt/ros/overlay/log
 
 # Clean up source code and caches
@@ -114,6 +131,17 @@ RUN apt-get update \
     ros-jazzy-image-transport \
     ros-jazzy-image-transport-plugins \
     ros-jazzy-std-srvs \
+    ros-jazzy-cv-bridge \
+    ros-jazzy-diagnostic-msgs \
+    ros-jazzy-image-geometry \
+    ros-jazzy-pcl-conversions \
+    ros-jazzy-pcl-ros \
+    ros-jazzy-rclcpp-action \
+    ros-jazzy-rclcpp-components \
+    ros-jazzy-tf2 \
+    ros-jazzy-tf2-geometry-msgs \
+    ros-jazzy-tf2-ros \
+    ros-jazzy-visualization-msgs \
     wget && \
     wget -O ensenso.deb "https://download.optonic.com/s/ensensosdk/download?files=ensenso-sdk-${ENSENSO_VERSION}-x64.deb" && \
     apt-get install -y ./ensenso.deb && \
